trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md
    - azure-pipeline.png
    
pr: none

variables:
  terraformVersion: 0.12.26
  tfFilesArtifactName: 'tf-files'
  skipComponentGovernanceDetection: true
  
pool:
 #vmImage: 'ubuntu-latest'
 name: mabenoittesttf

stages:
- stage: 'prepare'
  displayName: 'prepare'
  jobs:
  - job: 'prepare'
    displayName: 'prepare'
    steps:
    - publish: '$(system.defaultWorkingDirectory)/tf'
      artifact: $(tfFilesArtifactName)
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: $(terraformVersion)
    - script: |
        terraform init \
            -backend=false
        terraform validate
      workingDirectory: $(system.defaultWorkingDirectory)/tf
      failOnStderr: true
      displayName: 'terraform validate'
- template: azure-pipelines-tf-plan-apply-template.yml
  parameters:
    environment: dev
- template: azure-pipelines-tf-plan-apply-template.yml
  parameters:
    environment: prod
